language: node_js

node_js:
  - 10
dist: trusty
addons:
  chrome: stable
services:
  - postgresql
before_script:
  - npm install coverage
  - npm install -g nyc
  - psql -c 'create database teamwork_db_test;' -U postgres
script:
  - npm test
after_script:
 